### ISSUE TITLE
Task #873973 generated an exception

### ISSUE THREAD

**Issue by OpalMoonstride** [OffLuffy/SmoothSleep#2]
Spigot 1.13.2
Paper 40f5a94b
Smoothsleep v2.3.2
Error: https://pastebin.com/TrEpT4E2

I'm not positive when it occurs, but it seems to correlate with a player logging in/out, during other players sleeping. It occurred prior to my updating, so it seems to be in both the last version, and this one.

**Comment by OffLuffy** [comment]
Sorry for late reply, wasn't aware anyone was using the GitHub issue tracker. I'm more responsive if issues are reported on the [Spigot discussion page](https://www.spigotmc.org/threads/smoothsleep.194674/).

I'm closing this issue because the pastebin link is expired as well as being for an older version of the plugin. If you still have an issue, feel free to add details. Preferably on Spigot since I don't get notified of issues here.
